server:
  port: 8601
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost/market
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver