server:
  port: 8601
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    # имя базы данных - market
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
#      schema-locations: classpath*:database/schema.sql
#      data-locations: classpath*:database/data.sql